name: Build OpenWrt for specific target and release

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
  #schedule:
  #  - cron: "0 */2 * * *"

env:
  REMOTE_REPOSITORY: qosmio/openwrt-ipq
  REMOTE_BRANCH: main-nss
  CONFIG_FILE: ax3600.config
  CUSTOM_FILES_PATH: files/
  RELEASE_PREFIX: main-nss
  NSS_PACKAGES_REPOSITORY: qosmio/nss-packages
  NSS_PACKAGES_REPOSITORY_BRANCH: NSS-12.5-K6.x

jobs:
  check_commits:
    name: Check for new commits
    runs-on: ubuntu-24.04
    outputs:
      new_commits: ${{ steps.check_commits.outputs.new_commits }}
      latest_commit_sha: ${{ steps.check_commits.outputs.latest_commit_sha }}
      nss_packages_repo_new_commits: ${{ steps.check_commits.outputs.nss_packages_repo_new_commits }}
      nss_packages_repo_latest_commit_sha: ${{ steps.check_commits.outputs.nss_packages_repo_latest_commit_sha }}
    steps:
      - name: Check for new commits in both repositories
        id: check_commits
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          latest_sha=$(gh api "repos/${{ env.REMOTE_REPOSITORY }}/commits/${{ env.REMOTE_BRANCH }}" --jq .sha)
          packages_sha=$(gh api "repos/${{ env.NSS_PACKAGES_REPOSITORY }}/commits/${{ env.NSS_PACKAGES_REPOSITORY_BRANCH }}" --jq .sha)
          release_body=$(gh api "repos/${{ github.repository }}/releases/latest" --jq .body 2>/dev/null || echo "")

          new_commits=$([[ "$release_body" == *"$latest_sha"* ]] && echo "false" || echo "true")
          nss_new_commits=$([[ "$release_body" == *"$packages_sha"* ]] && echo "false" || echo "true")

          echo "new_commits=$new_commits" >> "$GITHUB_OUTPUT"
          echo "latest_commit_sha=$latest_sha" >> "$GITHUB_OUTPUT"
          echo "nss_packages_repo_new_commits=$nss_new_commits" >> "$GITHUB_OUTPUT"
          echo "nss_packages_repo_latest_commit_sha=$packages_sha" >> "$GITHUB_OUTPUT"

  build:
    name: Build OpenWrt
    needs: check_commits
    if: github.event_name == 'workflow_dispatch' || needs.check_commits.outputs.new_commits == 'true' || needs.check_commits.outputs.nss_packages_repo_new_commits == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget && sudo apt full-upgrade -y
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "builder_repo"

      - name: Add custom patches
        run: |
          if [ -d "builder_repo/patches" ] && [ "$(ls -A builder_repo/patches 2>/dev/null)" ]; then
            mv builder_repo/patches/* ./
            for patch in *.patch; do
              [ -f "$patch" ] && git apply --verbose "$patch"
            done
          fi

      - name: Update and install feeds
        run: ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Setup configuration and custom files
        run: |
          mv builder_repo/${{ env.CONFIG_FILE }} .config
          make defconfig -j$(nproc)
          mkdir -p ${{ env.CUSTOM_FILES_PATH }}
          [ -d "builder_repo/${{ env.CUSTOM_FILES_PATH }}" ] && mv builder_repo/${{ env.CUSTOM_FILES_PATH }}* ${{ env.CUSTOM_FILES_PATH }} || true

      - name: Build firmware
        run: |
          make download -j$(nproc) V=s
          make -j$(nproc) || make -j1 V=s  # Retry single-threaded on failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipq807x-images
          path: bin/targets/qualcommax/ipq807x

  release:
    name: Create release
    needs: [check_commits, build]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ipq807x-images
          path: firmware
      - name: Set release date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV
      - name: Publish release
        uses: softprops/action-gh-release@master
        with:
          files: firmware/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.RELEASE_DATE }}
          name: 🚀 OpenWrt Build Release ${{ env.RELEASE_DATE }}
          body: |
            ## 📦 OpenWrt Automated Build Release

            **Build Date:** ${{ env.RELEASE_DATE }}

            ### 🔄 Main Repository
            **Repository:** [${{ env.REMOTE_REPOSITORY }}](https://github.com/${{ env.REMOTE_REPOSITORY }})
            **Branch:** `${{ env.REMOTE_BRANCH }}`
            **Commit:** `${{ needs.check_commits.outputs.latest_commit_sha }}`

            ### 📦 NSS Packages
            **Repository:** [${{ env.NSS_PACKAGES_REPOSITORY }}](https://github.com/${{ env.NSS_PACKAGES_REPOSITORY }})
            **Branch:** `${{ env.NSS_PACKAGES_REPOSITORY_BRANCH }}`
            **Commit:** `${{ needs.check_commits.outputs.nss_packages_repo_latest_commit_sha }}`

            ### 📝 Build Information
            - **Target:** [Xiaomi Mi AIoT Router AX3600](https://openwrt.org/toh/xiaomi/ax3600)
            - **Configuration:** [`${{ env.CONFIG_FILE }}`](${{ env.CONFIG_FILE }})

            ### 📋 Notes
            - Automated build triggered by ${{ github.event_name }}
            - Previous releases are automatically cleaned up (keeping latest 2)
            ---
            _Generated by GitHub Actions 🤖_

      - name: Clean up old releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ github.repository }}/releases --paginate --jq '.[2:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
            gh api -X DELETE "repos/${{ github.repository }}/releases/$id" && gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/$tag" 2>/dev/null || true
          done
